# Generated by Django 2.0 on 2021-01-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionoption_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='genero',
        ),
    ]
