# Generated by Django 2.0 on 2021-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_questionoption_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='tipo',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('IMPERIALI', 'IMPERIALI'), ('HUNTINGTONHILL', 'HUNTINGTONHILL'), ('DANISH', 'DANISH'), ('DHONT', 'DHONT'), ('MULTIPREGUNTAS', 'MULTIPREGUNTAS'), ('SAINTELAGUE', 'SAINTELAGUE')], default='IDENTITY', max_length=20),
        ),
    ]
