# Generated by Django 2.0 on 2021-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_voting_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='numEscanos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
