# Generated by Django 2.0 on 2021-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voting_numescanos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='numEscanos',
        ),
        migrations.AddField(
            model_name='question',
            name='numEscanos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seats'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='tipo',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('IMPERIALI', 'IMPERIALI'), ('HUNTINGTONHILL', 'HUNTINGTONHILL'), ('DANISH', 'DANISH'), ('DHONT', 'DHONT'), ('MULTIPREGUNTAS', 'MULTIPREGUNTAS'), ('SAINTELAGUE', 'SAINTELAGUE')], default='IDENTITY', max_length=20, verbose_name='Count method'),
        ),
    ]
