# Generated by Django 2.0 on 2021-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20210108_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='numEscanos',
        ),
        migrations.AddField(
            model_name='voting',
            name='numEscanos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seats'),
        ),
    ]
