# Generated by Django 2.0 on 2021-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20210108_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='tipo',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('IMPERIALI', 'IMPERIALI'), ('HUNTINGTONHILL', 'HUNTINGTONHILL'), ('DANISH', 'DANISH'), ('DHONT', 'DHONT'), ('MULTIPREGUNTAS', 'MULTIPREGUNTAS'), ('SAINTELAGUE', 'SAINTELAGUE'), ('PREGUNTASPESO', 'PREGUNTASPESO')], default='IMPERIALI', max_length=20, verbose_name='Count method'),
        ),
    ]
